[server]
mode = "debug"
addr = "127.0.0.1:8080"
readTimeout = "60s"
writeTimeout = "60s"
maxHeaderBytes = 102400
pprofToken="dorkksdfoi23k"
[logger]
filename = "./logs/go101.log"
maxSize = 100
maxAge = 7
maxBackups = 10
compress = true
level = "debug"
[db]
driver = "sqlite"
host = "127.0.0.1"
port = 3306
user = "root"
password = "Abc@123"
name = "go101.sqlite"
[storage]
driver = "local"
[storage.minio]
endpoint = "192.168.0.53:9000"
useSSL = false
accessKeyID = "JXrDXdWwNQmJSfQkGgN7"
secretAccessKey = "LLAvfdyNWecV5py5jCHK0IRaVQos43KvO2KxJ1F5"
bucket = "go101"
region = "cn-east-1"
[storage.local]
rootPath = "data/uploads"