[server]
mode = "debug"
addr = "127.0.0.1:8080"
readTimeout = "60s"
writeTimeout = "60s"
maxHeaderBytes = 102400
pprof=true
[logger]
filename = "./logs/go101.log"
maxSize = 100
maxAge = 7
maxBackups = 10
compress = true
level = "debug"
[db]
driver = "sqlite"
host = "127.0.0.1"
port = 3306
user = "root"
password = "Abc@123"
name = "go101.sqlite"
